import Head from 'next/head'
import { useQuery } from 'urql'
import { PRODUCT_QUERY } from '../lib/query'
import { Inter } from '@next/font/google'
import styles from '../styles/Home.module.css'
import Product from '../components/Product'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  const [results] = useQuery({query:PRODUCT_QUERY})
  
  const {data, fetching, error} = results
  if(fetching) return(<p>loading....</p>)
  if(error) return(<p>loading.Error...</p>)
  console.log (data.products.data)
  const products = data.products.data
  return (
    <div className="w-full">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
      <main className={styles.main}>
       
      {products.map(product=>(<h1 key={product.attributes._id}>  <Product product={product}/></h1>))}
     
      </main>
      
    </div>
  )
}


